apptodo/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth import get_user_model
User = get_user_model()


urlpatterns = [
    path('home/', views.home, name = "home"),
    path('signup/', views.signup, name = "signup"),
    path('login/', auth_views.LoginView.as_view(template_name="login.html"), name = "login"),
    path('logout/', auth_views.LogoutView.as_view(template_name="logout.html"), name = "logout"),
    path('addtask/', views.addtask, name = "addtask"),
    path('delete/<int:pk>/', views.delete_task, name = "delete"),
    path('complete/<int:pk>/', views.complete_task, name="complete"),
    path('creategroup/', views.creategroup, name = "creategroup"),
    path('allgroups/', views.allgroups, name = "allgroups"),
    path('group/<int:pk>/', views.group, name = "grouppage"),
    path('group/<int:pk>/add/', views.group_member_add, name = "groupmemberadd"),
    path('group/<int:id>/delete/<int:pk>/', views.delete_grouptask, name = "delete_grouptask"),
    path('group/<int:id>/complete/<int:pk>/', views.complete_grouptask, name="complete_grouptask"),
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('apptodo.urls')),
    path('api/', include('todo_api.urls')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo_api/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class MyUser(AbstractUser):
    email = models.EmailField(max_length=256, unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']


class Task(models.Model):
    """Stores tasks of users"""
    task = models.CharField(max_length=200, blank=False)
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE, null = False, blank=True)
    posted_on = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default = False, blank = True)

    def __str__(self):
        return self.task

    class Meta:
        ordering = ['-posted_on']


class Group(models.Model):
    """Stores information of TaskGroups"""
    group_name = models.CharField(max_length = 40, blank = False)
    created_by = models.ForeignKey(MyUser, on_delete=models.CASCADE, null = False)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.group_name


class Member(models.Model):
    """Stores pairs of Group and User whenever a User is added"""
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE, null = False)
    group_name = models.ForeignKey(Group, on_delete=models.CASCADE, null = False)

    class Meta:
        unique_together = ('user', 'group_name')

    def __str__(self):
        return str(self.user) + " in " + str(self.group_name)


class GroupTask(models.Model):
    """Stores tasks of TaskGroups"""
    task = models.CharField(max_length=200, blank=False)
    group = models.ForeignKey(Group, on_delete=models.CASCADE, null = False)
    added_by = models.ForeignKey(MyUser, on_delete=models.CASCADE, null=False)
    added_on = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False, blank=False)

apptodo/forms.py
from django import forms
from todo_api.models import Task, Group, GroupTask, Member
from django.contrib.auth.forms import UserCreationForm
from todo_api.models import MyUser, Task


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = MyUser
        fields = UserCreationForm.Meta.fields + ('email',)



class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ('task', )


class GroupForm(forms.Form):
    """Not a model form as data to be added in two models"""
    group_name = forms.CharField(max_length=40)


class MemberAddForm(forms.ModelForm):

    class Meta:
        model = Member
        fields = ['user']


class TaskGroupTaskForm(forms.ModelForm):

    class Meta:
        model = GroupTask
        fields = ["task",]

apptodo/views.py
from django.shortcuts import render, redirect
from todo_api.models import Task, GroupTask, Group, Member
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import TaskForm, GroupForm, MemberAddForm, TaskGroupTaskForm, CustomUserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
User = get_user_model()


def home(request):
    return render(request, "home.html")


def signup(request):
    """Registers new user"""
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()

            messages.success(request, "Account successfully created")
            return redirect('login')

    form = CustomUserCreationForm()
    context = {
        'form': form,
    }

    return render(request, "signup.html", context)


@login_required
def addtask(request):
    """Displays and adds task to task list of a user"""
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            post = form.save(commit = False)
            post.user = request.user
            post.save()
            messages.success(request, "Task added successfully")
        else:
            messages.error(request, "failed")

    form = TaskForm()
    context = {
        'form' : form,

    }
    return render(request, 'taskpage.html', context )


@login_required
def delete_task(request, pk):
    """Deletes task from task list of a user"""
    task = Task.objects.get(pk = pk)

    task.delete()
    return redirect('addtask')


@login_required
def complete_task(request ,pk):
    """Marks task as done"""
    task = Task.objects.get(pk = pk)

    task.status = True
    task.save()
    return redirect('addtask')


@login_required
def creategroup(request):
    """Creates a TaskGroup"""
    if request.method == "POST":
        form = GroupForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['group_name']
            group = Group(group_name = name, created_by = request.user)
            group.save()
            usergroup = Member(user = request.user, group_name = group)
            usergroup.save()

    form = GroupForm()
    context = {
        'form': form,
    }
    return render(request, "create_group.html", context)


@login_required
def allgroups(request):
    groups = Member.objects.filter(user = request.user)
    context = {
        "groups": groups,
    }
    return render(request, "allgroups.html", context)

@login_required
def group_member_add(request, pk):
    """Adds member to a TaskGroup"""
    group1 = Group.objects.get(pk = pk)

    if request.method == "POST":
        form = MemberAddForm(request.POST)
        if form.is_valid():
            post = form.save(commit = False)
            post.group_name = group1
            post.save()
            messages.success(request, "Added!", fail_silently=True)
        else:
            messages.error(request, "not added!")

    form = MemberAddForm()

    context = {
        "group_list": group1,
        "form": form,
    }

    return render(request, "group_member_add.html", context)


@login_required
def group(request, pk):
    """Displays and add tasks of TaskGrouo"""
    groupx = Group.objects.get(pk = pk)
    if request.method == "POST":
        form = TaskGroupTaskForm(request.POST)
        if form.is_valid():
            post = form.save(commit = False)
            post.added_by = request.user
            post.group = groupx
            post.save()
            messages.success(request, "Task added successfully")
        else:
            messages.error(request, "failed")

    form = TaskGroupTaskForm()
    context = {
        'form' : form,
        'group': groupx,
    }
    return render(request, 'group_page.html', context )


@login_required
def delete_grouptask(request, id, pk):
    """Deletes task from TaskGroup"""
    task = GroupTask.objects.get(pk = pk)
    task.delete()
    return redirect('grouppage', pk = id)


@login_required
def complete_grouptask(request, id, pk):
    """Marks task as complete from TaskGroup"""
    task = GroupTask.objects.get(pk = pk)

    task.status = True
    task.save()
    return redirect('grouppage', pk = id)

apptodo/templates/allgroups.html
{% extends "base.html" %}

{% block title %}
My Groups
{% endblock %}

{% block content %}
<div class="container-fluid text-center py-3 border">

        <h1>Groups</h1>

        <ul class="list-inline mx-auto justify-content-center">
            {% for group in groups %}
            <li class="list-inline-item"><h3><a href="{% url 'grouppage' group.group_name.pk %}">{{ group.group_name }}</a></h3></li>
            <br>
            {% endfor %}
        </ul>

        <a class = "btn btn-primary text-white" href = "{% url 'creategroup' %}">Add Group</a>

</div>
{% endblock %}

apptodo/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    {% load static %}
    <link rel = "stylesheet" href="{% static 'frontend/style.css' %}">
</head>
<body>
 
    

        {% if user.is_authenticated %}
        <nav class = "navbar navbar-expand-sm bg-dark navbar-dark">
            <a class="navbar-brand" href = "{% url 'home' %}">Todo</a>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href = "{% url 'allgroups' %}" class = "nav-link">My Groups</a>
                </li>
                <li class="nav-item">
                    <a href = "{% url 'addtask' %}" class = "nav-link">My Tasks</a>
                </li>
                <li class="nav-item">
                    <a href = "{% url 'creategroup' %}" class = "nav-link">Create Group</a>
                </li>
                <li class="nav-item">
                    <a href = "{% url 'logout' %}" class = "nav-link">Log Out</a>
                </li>
            </ul>
        </nav>

        {% else %}
        <nav class = "navbar navbar-expand-sm bg-dark navbar-dark justify-content-center">
            <a class="navbar-brand" href = "{% url 'home' %}">Todo</a>
        </nav>
        {% endif %}

        
    {% if messages %}
    {% for m in messages %}
        {{ m }}
    {% endfor %}
    {% endif %}

    {% block content %}
    {% endblock %}

</body>
</html>

apptodo/templates/create_group.html
{% extends "base.html" %}

{% block title %}
Create Group
{% endblock %}

{% block content %}
<div class="container-fluid text-center py-3 border">

        <h1>Create Group</h1>

        <form method="POST">
            {% csrf_token %}
            {% for h in form.hidden_fields %}
            {{h.errors}}
            {{h}}
            {% endfor %}

            {% for f in form.visible_fields %}

                {{f}}

            {% endfor %}
            <br>
            <button type = "submit" class = "btn btn-primary my-2">Add Group</button>
        </form>

    </div>
{% endblock %}

apptodo/templates/group_member_add.html
{% extends "base.html" %}

{% block title %}
{{ group_list.group_name }}
{% endblock %}

{% block content %}

<div class="container text-center py-3 text-center">
<h1>Group - {{ group_list.group_name }}</h1>

<form method="POST">
            {% csrf_token %}
            {% for h in form.hidden_fields %}
            {{h.errors}}
            {{h}}
            {% endfor %}

            {% for f in form.visible_fields %}

                {{f}}

            {% endfor %}
            <br>
            <button type = "submit" class = "btn btn-primary my-2">Add Member</button>
        </form>



    <ul class="list-inline mx-auto justify-content-center">
            {% for object in group_list.member_set.all %}
            <li class="list-inline-item"><h3>{{ object.user }}</h3></li>
            <br>
            {% endfor %}
        </ul>
</div>
{% endblock %}

apptodo/templates/group_page.html
{% extends "base.html" %}

{% block title %}
{{ group.group_name }}
{% endblock %}

{% block content %}




<div class="container-fluid text-center py-3">

        <h1>Group - {{ group.group_name }}</h1>


        <form method="POST">
            {% csrf_token %}
            {% for h in form.hidden_fields %}
            {{h.errors}}
            {{h}}
            {% endfor %}

            {% for f in form.visible_fields %}

                {{f}}

            {% endfor %}
            <br>
            <button type = "submit" class = "btn btn-primary my-2">Add Task</button>
        </form>



<ol class = "mt-5">
            {% for task in group.grouptask_set.all %}
            <hr class="m-0">
            <li class = "pt-2">
                <p class="float-left  mx-3 align-middle {% if task.status %} text-success {% else %} text-danger {% endif %}">{{ task.task }}</p>
                <a href = "{% url 'complete_grouptask' group.pk task.pk %}" class = "btn btn-sm btn-success float-right mx-3">Done</a>
                <a href = "{% url 'delete_grouptask' group.pk task.pk %}" class = "btn btn-sm btn-danger float-right mx-3">Delete</a>
            </li>
            <div class = "clear m-0 p-0"></div>
            {% endfor %}
            <hr class="m-0">
</ol>

<a href = "{% url 'groupmemberadd' group.pk %}">Manage Members</a>
</div>
{% endblock %}

apptodo/templates/home.html
{% extends "base.html" %}

{% block title %}
Home
{% endblock %}

{% block content %}
<div class="container-fluid text-center py-3">

    <a class = "btn btn-lg btn-outline-primary text-primary col-md-4 hov" href = "{% url 'login' %}">Log In</a>
    <br>
    <a class = "btn btn-lg btn-outline-success text-success col-md-4 mt-3 hov" href = "{% url 'signup' %}">Sign Up</a>

</div>
{% endblock %}

apptodo/templates/login.html
{% extends "base.html" %}

{% block title %}
Login
{% endblock %}

{% block content %}

<div class="container-fluid text-center py-3">

    <h1>Log In</h1>

    <form method="POST">
        {% csrf_token %}

        <p class = "text-danger">{{ form.non_field_errors }}</p>

        {% for h in forms.hidden_fields %}
        <p class = "text-danger">{{ h.errors }}
        {{ h }}</p>
        {% endfor %}

            <table class="mx-auto">
                {% for f in form.visible_fields %}
                <tr>
                    <td class="align-top">{{ f.label }}</td>
                    <td>
                        {{ f }}
                        <p class = "text-danger">{{ f.errors }}</p>
                        <p class = "text-info">{{ f.help_text }}</p>
                    </td>
                </tr>
                {% endfor %}
            </table>

            <button type = "submit" class = "btn btn-primary">Log In</button>

        </form>
    <p>Don't have an account?<br><a href = "{% url 'signup' %}">Sign Up</a></p>

</div>

{% endblock %}

apptodo/templates/logout.html
{% extends "base.html" %}
{% block title %}
Logout
{% endblock %}

{%block content %}
<h3>Successfully Logged Out!</h3>
<a href = "{% url 'login' %}">Login</a>
{% endblock %}

apptodo/templates/signup.html
{% extends "base.html" %}

{% block title %}
Signup
{% endblock %}

{% block content %}
<div class="container-fluid text-center py-3">

    <h1>Sign Up</h1>

    <form method="POST">
        {% csrf_token %}

        <p class = "text-danger">{{ form.non_field_errors }}</p>

        {% for h in forms.hidden_fields %}
        <p class = "text-danger">{{ h.errors }}
        {{ h }}</p>
        {% endfor %}

            <table class="mx-auto">
                {% for f in form.visible_fields %}
                <tr>
                    <td class="align-top">{{ f.label }}</td>
                    <td>
                        {{ f }}
                        <p class = "text-danger">{{ f.errors }}</p>
                        <p class = "text-info">{{ f.help_text }}</p>
                    </td>
                </tr>
                {% endfor %}
            </table>

            <button type = "submit" class = "btn btn-primary">Sign Up</button>

        </form>
    <p>Already have an account?<br><a href = "{% url 'login' %}">Log In</a></p>

</div>
{% endblock %}

apptodo/templates/taskpage.html
{% extends "base.html" %}

{% block title %}
Tasks
{% endblock %}

{% block content %}
<div class="container text-center py-3 text-center">
    <h1>Tasks</h1>
    <form method="POST">
        {% csrf_token %}
        {% for h in form.hidden_fields %}
        {{h.errors}}
        {{h}}
        {% endfor %}

        {% for f in form.visible_fields %}
            
            {{f}}
            
        {% endfor %}
        <br>
        <button type = "submit" class = "btn btn-primary my-2">Add Task</button>
    </form>

    <br>
        <ol class = "mt-5">
            {% for task in user.task_set.all %}
            <hr class="m-0">
            <li class = "pt-2">
                <p class="float-left  mx-3 align-middle {% if task.status %} text-success {% else %} text-danger {% endif %}">{{ task.task }}</p>
                <a href = "{% url 'complete' task.pk %}" class = "btn btn-sm btn-success float-right mx-3">Done</a>
                <a href = "{% url 'delete' task.pk %}" class = "btn btn-sm btn-danger float-right mx-3">Delete</a>
            </li>
            <div class = "clear m-0 p-0"></div>
            {% endfor %}
            <hr class="m-0">
        </ol>

    </div>


{% endblock %}




    

    